"""Conversation cluster ORM model and Pydantic schemas.

Defines the persistence layer and API schemas for topic clusters discovered
by LLM-guided clustering. Each cluster groups semantically similar conversations
and has a human-readable label generated by LLM.
"""

from __future__ import annotations

import uuid
from datetime import datetime

from pydantic import BaseModel as PydanticBase
from pydantic import ConfigDict
from sqlalchemy import Float, Index, Integer, String, Text
from sqlalchemy.orm import Mapped, mapped_column
from sqlalchemy.types import JSON

from hecate.models.base import BaseModel


class ConversationClusterModel(BaseModel):
    """ORM model for topic clusters.

    Each cluster groups semantically similar conversations. The centroid_embedding
    is stored as a JSON array for cross-dialect compatibility (SQLite/PostgreSQL).
    Quality metrics (DBI, Silhouette, Cohesion) are computed periodically to
    detect cluster degradation.

    Key fields:

    - **label** — LLM-generated human-readable topic label (e.g., "billing",
      "technical_support", "feature_request").
    - **centroid_embedding** — mean embedding of all conversations in the cluster.
      Stored as JSON array for cross-dialect compatibility.
    - **description** — LLM-generated description of the cluster's topic.
    - **conversation_count** — number of conversations assigned to this cluster.
    - **dbi_score** — Davies-Bouldin Index (lower is better, < 0.5 is good).
    - **silhouette_score** — Silhouette Score (higher is better, > 0.5 is good).
    - **cohesion_score** — intra-cluster cosine similarity (higher is better).
    """

    __tablename__ = "conversation_clusters"

    label: Mapped[str] = mapped_column(String(200), nullable=False)
    centroid_embedding: Mapped[list] = mapped_column(JSON, nullable=False)
    description: Mapped[str | None] = mapped_column(Text, nullable=True)
    conversation_count: Mapped[int] = mapped_column(Integer, nullable=False, default=0)

    # Quality metrics
    dbi_score: Mapped[float | None] = mapped_column(Float, nullable=True)
    silhouette_score: Mapped[float | None] = mapped_column(Float, nullable=True)
    cohesion_score: Mapped[float | None] = mapped_column(Float, nullable=True)

    __table_args__ = (
        Index("idx_clusters_label", "label"),
        Index("idx_clusters_count", "conversation_count"),
    )


class ConversationClusterCreateSchema(PydanticBase):
    """Schema for creating a new cluster."""

    model_config = ConfigDict(extra="forbid")

    label: str
    centroid_embedding: list[float]
    description: str | None = None


class ConversationClusterReadSchema(PydanticBase):
    """Schema for reading cluster data."""

    model_config = ConfigDict(from_attributes=True)

    id: uuid.UUID
    label: str
    description: str | None
    conversation_count: int
    dbi_score: float | None
    silhouette_score: float | None
    cohesion_score: float | None
    created_at: datetime
    updated_at: datetime
