"""Engine/service boundary contract (Ports and Adapters pattern).

This module defines EnginePort, the abstract interface that decouples the
execution engine from external capability services (LLM providers, tool runners,
knowledge bases, checkpoint storage, conversation history). The engine calls
these methods to perform I/O without importing any concrete service module.

**Why ports?** The engine is designed to be fully testable in isolation. By
depending on the EnginePort abstract interface rather than concrete service
implementations, unit tests can provide lightweight mocks or fakes. Production
code supplies an adapter that wires each method to the actual service layer.
This zero-dependency design keeps the engine framework-agnostic and allows
different deployment configurations to swap service implementations freely.
"""

from __future__ import annotations

from abc import ABC, abstractmethod
from collections.abc import AsyncGenerator
from typing import Any
from uuid import UUID


class EnginePort(ABC):
    """Boundary interface between the execution engine and external capability services.

    The engine calls these methods to invoke LLM, execute tools, query knowledge,
    and manage conversation/checkpoint state without importing any service module.
    """

    @abstractmethod
    def llm_invoke(self, messages: list[dict], config: dict) -> AsyncGenerator[str, None]:
        """Invoke an LLM with the given messages and return a stream of tokens.

        Args:
            messages: A list of message dicts (role, content) forming the conversation.
            config: Provider-specific configuration (model name, temperature, etc.).

        Yields:
            Token strings as they are generated by the LLM.
        """
        ...

    @abstractmethod
    async def tool_execute(self, name: str, args: dict, context: dict | None = None) -> Any:
        """Execute a tool by name with the given arguments.

        Args:
            name: The registered tool name.
            args: Keyword arguments to pass to the tool.
            context: Optional execution context (session, node, etc.).

        Returns:
            The tool's return value (type depends on the tool).
        """
        ...

    @abstractmethod
    async def knowledge_query(self, query: str, kb_ids: list[UUID]) -> list[dict]:
        """Query knowledge bases and return relevant document chunks.

        Args:
            query: The search query string.
            kb_ids: UUIDs of the knowledge bases to search.

        Returns:
            A list of document chunk dicts with content and metadata.
        """
        ...

    @abstractmethod
    async def checkpoint_save(self, state: dict) -> UUID:
        """Persist an execution state checkpoint and return its ID.

        Args:
            state: The full execution state to persist.

        Returns:
            A UUID identifying the saved checkpoint.
        """
        ...

    @abstractmethod
    async def checkpoint_load(self, checkpoint_id: UUID) -> dict:
        """Load a previously saved checkpoint by ID.

        Args:
            checkpoint_id: The UUID of the checkpoint to load.

        Returns:
            The checkpoint's state dict.
        """
        ...

    @abstractmethod
    async def conversation_load(self, session_id: UUID) -> list[dict]:
        """Load conversation message history for a session.

        Args:
            session_id: The session whose messages to load.

        Returns:
            A list of message dicts in chronological order.
        """
        ...

    @abstractmethod
    async def conversation_save(self, session_id: UUID, messages: list[dict]) -> None:
        """Persist conversation messages for a session.

        Args:
            session_id: The session to save messages for.
            messages: The list of message dicts to persist.
        """
        ...

    async def context_assemble(
        self,
        messages: list[dict],
        tools: list[dict] | None,
        session_id: UUID,
        model: str = "gpt-4o",
    ) -> dict:
        """Assemble optimized context for an LLM invocation (optional).

        Context Engineering capability — dynamically assembles messages and tools
        based on task phase, budget, and provider requirements.

        Default implementation returns messages and tools unchanged (pass-through).

        Args:
            messages: Raw conversation messages.
            tools: Available tool definitions.
            session_id: Current session identifier.
            model: Target LLM model.

        Returns:
            Dict with 'messages', 'tools', 'metadata' keys.
        """
        return {"messages": messages, "tools": tools, "metadata": {}}

    async def evidence_query(
        self,
        session_id: UUID,
        min_importance: float | None = None,
        limit: int = 100,
    ) -> list[dict]:
        """Query evidence records for a session (optional).

        Context Engineering capability — retrieves structured tool execution
        results with provenance tracking.

        Default implementation returns empty list.

        Args:
            session_id: Session to query evidence for.
            min_importance: Minimum importance score filter.
            limit: Maximum results to return.

        Returns:
            List of evidence record dicts.
        """
        return []

    async def agent_execute(
        self,
        agent_id: UUID,
        messages: list[dict],
        channel_snapshot: dict,
        context: dict | None = None,
        agent_definition: Any | None = None,
    ) -> dict:
        """Execute an agent by ID with isolated context (optional).

        Multi-Agent capability -- resolves the AgentModel, builds an isolated
        execution context (system prompt, tools, knowledge bases from the
        agent definition), invokes the LLM, and returns the response.

        Default implementation raises NotImplementedError. Concrete adapters
        MUST override this method in production deployments.

        Args:
            agent_id: UUID of the agent to execute.
            messages: Conversation messages to pass as input.
            channel_snapshot: Read-only snapshot of current channel state.
            context: Optional execution context (session, parent agent, etc.).
            agent_definition: Optional AgentDefinition for per-invocation overrides
                (tool whitelist/blacklist, context mode, model override, etc.).

        Returns:
            Dict with keys: ``response`` (str), ``usage`` (dict), and
            optionally ``tool_calls`` (list).

        Raises:
            ValueError: If the agent_id does not resolve to a valid agent.
        """
        raise NotImplementedError("agent_execute requires a concrete EnginePort adapter")

    async def tool_execute_sandbox(
        self,
        name: str,
        args: dict,
        context: dict | None = None,
    ) -> Any:
        """Execute a tool inside a sandboxed Docker container (optional).

        Sandbox capability — isolates tool execution with resource limits
        and timeout handling for untrusted or high-risk tools.

        Default implementation falls back to regular tool_execute.

        Args:
            name: The registered tool name.
            args: Keyword arguments to pass to the tool.
            context: Optional execution context.

        Returns:
            The tool's return value.
        """
        return await self.tool_execute(name, args, context)
