"""Engine/service boundary contract (Ports and Adapters pattern).

This module defines RuntimePort, the abstract interface that decouples the
execution engine from external capability services (LLM providers, tool runners,
knowledge bases, checkpoint storage, conversation history). The engine calls
these methods to perform I/O without importing any concrete service module.

**Why ports?** The engine is designed to be fully testable in isolation. By
depending on the RuntimePort abstract interface rather than concrete service
implementations, unit tests can provide lightweight mocks or fakes. Production
code supplies an adapter that wires each method to the actual service layer.
This zero-dependency design keeps the engine framework-agnostic and allows
different deployment configurations to swap service implementations freely.

**Test doubles**: ``StubRuntimePort`` (below) is the canonical test double.
Use this name when writing new tests; legacy test doubles (``StubPort``,
``_StubPort``, ``MockEnginePort``) remain valid for existing tests but are
not recommended for new code.
"""

from __future__ import annotations

from abc import ABC, abstractmethod
from collections.abc import AsyncGenerator
from dataclasses import dataclass
from typing import Any
from uuid import UUID


@dataclass(frozen=True)
class SpanContext:
    """Immutable context returned when a span is created via RuntimePort.

    Carries the IDs needed to correlate engine events with application-level traces.
    """

    span_id: str
    trace_id: str
    parent_id: str | None = None


class RuntimePort(ABC):
    """Boundary interface between the execution engine and external capability services.

    The engine calls these methods to invoke LLM, execute tools, query knowledge,
    and manage conversation/checkpoint state without importing any service module.
    """

    @abstractmethod
    def llm_invoke(self, messages: list[dict], config: dict) -> AsyncGenerator[str, None]:
        """Invoke an LLM with the given messages and return a stream of tokens.

        Args:
            messages: A list of message dicts (role, content) forming the conversation.
            config: Provider-specific configuration (model name, temperature, etc.).

        Yields:
            Token strings as they are generated by the LLM.
        """
        ...

    @abstractmethod
    async def tool_execute(self, name: str, args: dict, context: dict | None = None) -> Any:
        """Execute a tool by name with the given arguments.

        Args:
            name: The registered tool name.
            args: Keyword arguments to pass to the tool.
            context: Optional execution context (session, node, etc.).

        Returns:
            The tool's return value (type depends on the tool).
        """
        ...

    @abstractmethod
    async def knowledge_query(self, query: str, kb_ids: list[UUID]) -> list[dict]:
        """Query knowledge bases and return relevant document chunks.

        Args:
            query: The search query string.
            kb_ids: UUIDs of the knowledge bases to search.

        Returns:
            A list of document chunk dicts with content and metadata.
        """
        ...

    @abstractmethod
    async def checkpoint_save(self, state: dict) -> UUID:
        """Persist an execution state checkpoint and return its ID.

        Args:
            state: The full execution state to persist.

        Returns:
            A UUID identifying the saved checkpoint.
        """
        ...

    @abstractmethod
    async def checkpoint_load(self, checkpoint_id: UUID) -> dict:
        """Load a previously saved checkpoint by ID.

        Args:
            checkpoint_id: The UUID of the checkpoint to load.

        Returns:
            The checkpoint's state dict.
        """
        ...

    @abstractmethod
    async def conversation_load(self, session_id: UUID) -> list[dict]:
        """Load conversation message history for a session.

        Args:
            session_id: The session whose messages to load.

        Returns:
            A list of message dicts in chronological order.
        """
        ...

    @abstractmethod
    async def conversation_save(self, session_id: UUID, messages: list[dict]) -> None:
        """Persist conversation messages for a session.

        Args:
            session_id: The session to save messages for.
            messages: The list of message dicts to persist.
        """
        ...

    @abstractmethod
    async def create_span(
        self,
        name: str,
        parent_id: str | None = None,
        attributes: dict[str, Any] | None = None,
    ) -> SpanContext | None:
        """Create an observability span for tracking execution.

        Called by the engine at execution boundaries (node start/end, LLM calls,
        tool calls). Returns None if tracing is disabled or no trace context exists.

        Args:
            name: Span name (e.g., "node:agent_1", "llm:gpt-4o").
            parent_id: Optional parent span ID for hierarchical nesting.
            attributes: Optional key-value pairs to attach to the span.

        Returns:
            SpanContext with span/trace IDs, or None if tracing is inactive.
        """
        ...

    @abstractmethod
    async def end_span(
        self,
        span_id: str,
        output_data: dict[str, Any] | None = None,
        usage: dict[str, int] | None = None,
    ) -> None:
        """End an observability span and record its output.

        No-op if the span_id does not correspond to an active span.

        Args:
            span_id: The span to finalize.
            output_data: Optional output data from the span's operation.
            usage: Optional token usage or resource consumption data.
        """
        ...

    async def llm_invoke_structured(
        self,
        messages: list[dict],
        config: dict,
    ) -> AsyncGenerator[dict[str, Any], None]:
        """Invoke LLM with structured response yielding content and optional tool_calls (optional).

        Enables the engine layer's Pregel chat graph tool-calling loop to detect when
        the LLM requested tools and route execution through ``check_tools`` /
        ``tool_call`` nodes. Chunks are dicts with keys:

        - ``content`` (str | None): text token delta; ``None`` when this chunk carries
          only structured metadata.
        - ``tool_calls`` (list[dict] | None): accumulated tool calls; ``None`` if the
          LLM did not request any tools in this response.

        Default implementation delegates to ``llm_invoke``, collects all tokens, and
        yields a single chunk ``{"content": <full text>, "tool_calls": None}``.
        Concrete adapters SHOULD override this method to surface structured
        ``tool_calls`` from the underlying LLM service.

        This is an optional method — concrete RuntimePort implementations are not
        required to override it. Non-overriding ports degrade to plain token-stream
        semantics and engine tool-calling detection will simply not activate.

        Args:
            messages: Conversation messages for the LLM.
            config: Provider-specific configuration (model, tools, etc.).

        Yields:
            Structured chunk dicts as described above.
        """
        tokens: list[str] = []
        async for token in self.llm_invoke(messages=messages, config=config):
            tokens.append(token)
        yield {"content": "".join(tokens), "tool_calls": None}

    async def context_assemble(
        self,
        messages: list[dict],
        tools: list[dict] | None,
        session_id: UUID,
        model: str = "gpt-4o",
    ) -> dict:
        """Assemble optimized context for an LLM invocation (optional).

        Context Engineering capability — dynamically assembles messages and tools
        based on task phase, budget, and provider requirements.

        Default implementation returns messages and tools unchanged (pass-through).

        Args:
            messages: Raw conversation messages.
            tools: Available tool definitions.
            session_id: Current session identifier.
            model: Target LLM model.

        Returns:
            Dict with 'messages', 'tools', 'metadata' keys.
        """
        return {"messages": messages, "tools": tools, "metadata": {}}

    async def evidence_query(
        self,
        session_id: UUID,
        min_importance: float | None = None,
        limit: int = 100,
    ) -> list[dict]:
        """Query evidence records for a session (optional).

        Context Engineering capability — retrieves structured tool execution
        results with provenance tracking.

        Default implementation returns empty list.

        Args:
            session_id: Session to query evidence for.
            min_importance: Minimum importance score filter.
            limit: Maximum results to return.

        Returns:
            List of evidence record dicts.
        """
        return []

    async def agent_execute(
        self,
        agent_id: UUID,
        messages: list[dict],
        channel_snapshot: dict,
        context: dict | None = None,
        agent_definition: Any | None = None,
    ) -> dict:
        """Execute an agent by ID with isolated context (optional).

        Multi-Agent capability -- resolves the AgentModel, builds an isolated
        execution context (system prompt, tools, knowledge bases from the
        agent definition), invokes the LLM, and returns the response.

        Default implementation raises NotImplementedError. Concrete adapters
        MUST override this method in production deployments.

        Args:
            agent_id: UUID of the agent to execute.
            messages: Conversation messages to pass as input.
            channel_snapshot: Read-only snapshot of current channel state.
            context: Optional execution context (session, parent agent, etc.).
            agent_definition: Optional AgentDefinition for per-invocation overrides
                (tool whitelist/blacklist, context mode, model override, etc.).

        Returns:
            Dict with keys: ``response`` (str), ``usage`` (dict), and
            optionally ``tool_calls`` (list).

        Raises:
            ValueError: If the agent_id does not resolve to a valid agent.
        """
        raise NotImplementedError("agent_execute requires a concrete RuntimePort adapter")

    async def tool_execute_sandbox(
        self,
        name: str,
        args: dict,
        context: dict | None = None,
    ) -> Any:
        """Execute a tool inside a sandboxed Docker container (optional).

        When the sandbox container pool is enabled, executes inside a
        pooled container. Otherwise falls back to regular tool_execute.

        Concrete adapters that support sandbox execution MUST override this
        method. The default implementation here is a pass-through to
        ``tool_execute`` — it deliberately does NOT import the sandbox service
        from ``hecate.services.sandbox`` so that ``engine/`` remains
        dependency-free at the module level. Sandbox routing is wired in by
        the harness / orchestrator via a concrete adapter.

        Args:
            name: The registered tool name.
            args: Keyword arguments to pass to the tool.
            context: Optional execution context.

        Returns:
            The tool's return value.
        """
        return await self.tool_execute(name, args, context)

    async def workflow_execute(
        self,
        workflow_id: UUID,
        input_data: dict,
        context: dict | None = None,
    ) -> dict:
        """Execute a workflow by ID with the given input (optional).

        Agent-Workflow embedding capability — enables agents to invoke
        workflows as callable tools via the SkillRegistry.

        Default implementation raises NotImplementedError. Concrete adapters
        MUST override this method to enable workflow-as-tool invocation.

        Args:
            workflow_id: UUID of the workflow to execute.
            input_data: Input data for the workflow.
            context: Optional execution context (session, parent agent, etc.).

        Returns:
            Dict with keys: ``output`` (Any), ``status`` (str).

        Raises:
            ValueError: If the workflow_id does not resolve to a valid workflow.
        """
        raise NotImplementedError("workflow_execute requires a concrete RuntimePort adapter")


class StubRuntimePort(RuntimePort):
    """Canonical test double for ``RuntimePort``.

    Provides minimal no-op implementations of all abstract methods and the
    default behavior for all optional methods. Use this class when writing
    new tests against ``RuntimePort``.

    Existing tests may use legacy names (``StubPort``, ``_StubPort``,
    ``MockEnginePort``) that subclass ``RuntimePort`` directly. Those names
    remain valid and are not deprecated by this PR.
    """

    async def llm_invoke(
        self,
        messages: list[dict],
        config: dict,
    ) -> AsyncGenerator[str, None]:
        """Yield a single deterministic token for tests."""
        yield "stub-response"

    async def tool_execute(
        self,
        name: str,
        args: dict,
        context: dict | None = None,
    ) -> Any:
        return {"name": name, "args": args, "context": context}

    async def knowledge_query(self, query: str, kb_ids: list[UUID]) -> list[dict]:
        return []

    async def checkpoint_save(self, state: dict) -> UUID:
        return UUID(int=0)

    async def checkpoint_load(self, checkpoint_id: UUID) -> dict:
        return {}

    async def conversation_load(self, session_id: UUID) -> list[dict]:
        return []

    async def conversation_save(self, session_id: UUID, messages: list[dict]) -> None:
        return None

    async def create_span(
        self,
        name: str,
        parent_id: str | None = None,
        attributes: dict[str, Any] | None = None,
    ) -> SpanContext | None:
        return None

    async def end_span(
        self,
        span_id: str,
        output_data: dict[str, Any] | None = None,
        usage: dict[str, int] | None = None,
    ) -> None:
        return None
