"""Engine/service boundary contract (Ports and Adapters pattern).

This module defines EnginePort, the abstract interface that decouples the
execution engine from external capability services (LLM providers, tool runners,
knowledge bases, checkpoint storage, conversation history). The engine calls
these methods to perform I/O without importing any concrete service module.

**Why ports?** The engine is designed to be fully testable in isolation. By
depending on the EnginePort abstract interface rather than concrete service
implementations, unit tests can provide lightweight mocks or fakes. Production
code supplies an adapter that wires each method to the actual service layer.
This zero-dependency design keeps the engine framework-agnostic and allows
different deployment configurations to swap service implementations freely.
"""

from __future__ import annotations

from abc import ABC, abstractmethod
from collections.abc import AsyncGenerator
from typing import Any
from uuid import UUID


class EnginePort(ABC):
    """Boundary interface between the execution engine and external capability services.

    The engine calls these methods to invoke LLM, execute tools, query knowledge,
    and manage conversation/checkpoint state without importing any service module.
    """

    @abstractmethod
    async def llm_invoke(self, messages: list[dict], config: dict) -> AsyncGenerator[str, None]:
        """Invoke an LLM with the given messages and return a stream of tokens.

        Args:
            messages: A list of message dicts (role, content) forming the conversation.
            config: Provider-specific configuration (model name, temperature, etc.).

        Yields:
            Token strings as they are generated by the LLM.
        """
        ...

    @abstractmethod
    async def tool_execute(self, name: str, args: dict, context: dict | None = None) -> Any:
        """Execute a tool by name with the given arguments.

        Args:
            name: The registered tool name.
            args: Keyword arguments to pass to the tool.
            context: Optional execution context (session, node, etc.).

        Returns:
            The tool's return value (type depends on the tool).
        """
        ...

    @abstractmethod
    async def knowledge_query(self, query: str, kb_ids: list[UUID]) -> list[dict]:
        """Query knowledge bases and return relevant document chunks.

        Args:
            query: The search query string.
            kb_ids: UUIDs of the knowledge bases to search.

        Returns:
            A list of document chunk dicts with content and metadata.
        """
        ...

    @abstractmethod
    async def checkpoint_save(self, state: dict) -> UUID:
        """Persist an execution state checkpoint and return its ID.

        Args:
            state: The full execution state to persist.

        Returns:
            A UUID identifying the saved checkpoint.
        """
        ...

    @abstractmethod
    async def checkpoint_load(self, checkpoint_id: UUID) -> dict:
        """Load a previously saved checkpoint by ID.

        Args:
            checkpoint_id: The UUID of the checkpoint to load.

        Returns:
            The checkpoint's state dict.
        """
        ...

    @abstractmethod
    async def conversation_load(self, session_id: UUID) -> list[dict]:
        """Load conversation message history for a session.

        Args:
            session_id: The session whose messages to load.

        Returns:
            A list of message dicts in chronological order.
        """
        ...

    @abstractmethod
    async def conversation_save(self, session_id: UUID, messages: list[dict]) -> None:
        """Persist conversation messages for a session.

        Args:
            session_id: The session to save messages for.
            messages: The list of message dicts to persist.
        """
        ...
